/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject2;

public class App {
    public static void main(String[] args) {
        App aplicacao = new App();
        pessoa p1 = new pessoa ("ronaldo");
        automovel aa1 = new automovel ("carro");
        piloto cc1 = new piloto ("roger");
        carro crr1 = new carro ("gol");
    }
}
